/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    ICustomSearch: typeof import('~icons/custom/search')['default']
    IDeviconTowergit: typeof import('~icons/devicon/towergit')['default']
    IMdiAccountBox: typeof import('~icons/mdi/account-box')['default']
    IMdiBookSearchOutline: typeof import('~icons/mdi/book-search-outline')['default']
  }
}
